version: '3.4'

services:
  app:
    container_name: go-api-sample-todo
    build:
      context: .
      dockerfile: ./Dockerfile.local
    ports:
      - 80:8080
    tty: true
    volumes:
      - .:/go/src/app
    environment:
      - DATABASE_HOST=mysql-db
      - DATABASE_PORT=3306
      - DATABASE_NAME=todo-app
      - DATABASE_USER=todo-app
      - DATABASE_PASSWORD=todo-app
  mysql:
      image: mysql:5.7
      container_name: mysql-db
      ports:
        - 3306:3306
      volumes:
        - ./migrations:/docker-entrypoint-initdb.d
      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: todo-app
          MYSQL_USER: todo-app
          MYSQL_PASSWORD: todo-app
          TZ: 'Asia/Tokyo'